import crypto from "node:crypto";

/**
 * Moby/Docker-style word lists (subset of names-generator).
 * @see https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go
 */
const ADJECTIVES = [
  "admiring",
  "adoring",
  "agitated",
  "amazing",
  "angry",
  "awesome",
  "blissful",
  "bold",
  "boring",
  "brave",
  "clever",
  "cocky",
  "compassionate",
  "competent",
  "condescending",
  "confident",
  "cranky",
  "dazzling",
  "determined",
  "distracted",
  "dreamy",
  "eager",
  "ecstatic",
  "elated",
  "elegant",
  "eloquent",
  "epic",
  "fervent",
  "festive",
  "flamboyant",
  "focused",
  "friendly",
  "frosty",
  "funny",
  "gallant",
  "gifted",
  "goofy",
  "gracious",
  "happy",
  "hardcore",
  "heuristic",
  "hopeful",
  "hungry",
  "infallible",
  "inspiring",
  "jolly",
  "jovial",
  "keen",
  "kind",
  "laughing",
  "loving",
  "lucid",
  "modest",
  "musing",
  "naughty",
  "nice",
  "nifty",
  "nostalgic",
  "objective",
  "optimistic",
  "peaceful",
  "pedantic",
  "pensive",
  "practical",
  "priceless",
  "quirky",
  "quizzical",
  "relaxed",
  "reverent",
  "romantic",
  "sad",
  "serene",
  "sharp",
  "silly",
  "sleepy",
  "stoic",
  "stupefied",
  "suspicious",
  "tender",
  "thirsty",
  "trusting",
  "vibrant",
  "vigilant",
  "vigorous",
  "wizardly",
  "wonderful",
  "youthful",
  "zealous",
  "zen",
] as const;

const NAMES = [
  "albattani",
  "allen",
  "archimedes",
  "ardinghelli",
  "aryabhata",
  "babbage",
  "banach",
  "bardeen",
  "bartik",
  "bassi",
  "bell",
  "bhabha",
  "bhaskara",
  "black",
  "bohr",
  "boyd",
  "brahmagupta",
  "brattain",
  "brown",
  "carson",
  "chandrasekhar",
  "clarke",
  "colden",
  "cori",
  "cray",
  "curie",
  "darwin",
  "davinci",
  "dijkstra",
  "edison",
  "einstein",
  "elion",
  "engelbart",
  "euclid",
  "euler",
  "faraday",
  "fermat",
  "fermi",
  "feynman",
  "franklin",
  "galileo",
  "gates",
  "goldberg",
  "goldstine",
  "goldwasser",
  "hawking",
  "heisenberg",
  "hopper",
  "hypatia",
  "jackson",
  "jennings",
  "jepsen",
  "johnson",
  "kalam",
  "kare",
  "keller",
  "kepler",
  "khorana",
  "kilby",
  "kirch",
  "knuth",
  "lalande",
  "lamarr",
  "lamport",
  "leakey",
  "leavitt",
  "lichterman",
  "liskov",
  "lovelace",
  "mayer",
  "mccarthy",
  "mcclintock",
  "mclean",
  "meitner",
  "meninsky",
  "merkle",
  "mestorf",
  "minsky",
  "mirzakhani",
  "moore",
  "morse",
  "moser",
  "napier",
  "nash",
  "neumann",
  "newton",
  "nightingale",
  "nobel",
  "noether",
  "noyce",
  "pare",
  "pascal",
  "pasteur",
  "payne",
  "perlman",
  "pike",
  "poincare",
  "ptolemy",
  "raman",
  "ramanujan",
  "ride",
  "ritchie",
  "rosalind",
  "saha",
  "sammet",
  "shannon",
  "shaw",
  "shockley",
  "sinoussi",
  "snyder",
  "spence",
  "stonebraker",
  "sutherland",
  "swanson",
  "tesla",
  "thompson",
  "torvalds",
  "turing",
  "visvesvaraya",
  "volhard",
  "wilson",
  "wing",
  "wozniak",
  "wright",
  "yonath",
] as const;

const FALLBACK = "Georgia Tech Student";

function pickIndex(seed: string, size: number, salt: number): number {
  const hash = crypto
    .createHash("sha256")
    .update(seed)
    .update(`:${salt}`)
    .digest();

  return hash.readUInt32BE(0) % size;
}

function titleCase(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

/** Deterministic Docker-style alias from encrypted authorId (e.g. `Focused Curie`). */
export function getAnonymousDisplayName(
  authorId: string | null | undefined,
): string {
  if (!authorId) {
    return FALLBACK;
  }

  const adjective = ADJECTIVES[pickIndex(authorId, ADJECTIVES.length, 0)];
  const name = NAMES[pickIndex(authorId, NAMES.length, 1)];

  return `${titleCase(adjective)} ${titleCase(name)}`;
}
