// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Textbook = {
  _type: "textbook";
  name?: string;
  url?: string;
};

export type Syllabus = {
  _type: "syllabus";
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  url?: string;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  course?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "course";
  };
  semester?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "semester";
  };
  body?: string;
  rating?: number;
  difficulty?: number;
  workload?: number;
  authorId?: string;
};

export type Semester = {
  _id: string;
  _type: "semester";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  term?: "spring" | "summer" | "fall";
  startDate?: string;
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  acronym?: string;
  url?: string;
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  codes?: Array<string>;
  programs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "program";
  }>;
  description?: string;
  creditHours?: number;
  syllabus?: Syllabus;
  textbooks?: Array<
    {
      _key: string;
    } & Textbook
  >;
  officialURL?: string;
  notesURL?: string;
  tags?: Array<string>;
  isDeprecated?: boolean;
  isFoundational?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Textbook
  | Syllabus
  | Review
  | Semester
  | Program
  | Course
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/queries/index.ts
// Variable: RECENT_REVIEWS_QUERY
// Query: *[_type == 'review']{  _id,  _createdAt,  body,  rating,  difficulty,  workload,  authorId,  semester->{    startDate,    term  },  course->{    name,    "slug": slug.current,  }} | order(_createdAt desc)[0...100]
export type RECENT_REVIEWS_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  body: string | null;
  rating: number | null;
  difficulty: number | null;
  workload: number | null;
  authorId: string | null;
  semester: {
    startDate: string | null;
    term: "fall" | "spring" | "summer" | null;
  } | null;
  course: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == 'course'] {  "slug": slug.current,}
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: COURSE_WITH_REVIEWS_QUERY
// Query: *[_type == 'course' && slug.current == $slug]{  ...,  "slug": slug.current,  "syllabusUrl": coalesce(syllabus.file.asset->url, syllabus.url),  programs[]->{acronym},  "reviews": *[_type == 'review' && references(^._id)]{    _id,    _createdAt,    body,    rating,    difficulty,    workload,    authorId,    "course": null,    semester->{      startDate,      term    },  } | order(created desc)}[0]
export type COURSE_WITH_REVIEWS_QUERY_RESULT = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  codes?: Array<string>;
  programs: Array<{
    acronym: string | null;
  }> | null;
  description?: string;
  creditHours?: number;
  syllabus?: Syllabus;
  textbooks?: Array<
    {
      _key: string;
    } & Textbook
  >;
  officialURL?: string;
  notesURL?: string;
  tags?: Array<string>;
  isDeprecated?: boolean;
  isFoundational?: boolean;
  syllabusUrl: string | null;
  reviews: Array<{
    _id: string;
    _createdAt: string;
    body: string | null;
    rating: number | null;
    difficulty: number | null;
    workload: number | null;
    authorId: string | null;
    course: null;
    semester: {
      startDate: string | null;
      term: "fall" | "spring" | "summer" | null;
    } | null;
  }>;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: COURSE_REVIEWS_PAGE_METADATA_QUERY
// Query: *[_type == 'course' && slug.current == $slug] {  name}[0]
export type COURSE_REVIEWS_PAGE_METADATA_QUERY_RESULT = {
  name: string | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: REVIEW_IDS_QUERY
// Query: *[_type == 'review'] {  "id": _id}[0...$limit]
export type REVIEW_IDS_QUERY_RESULT = Array<{
  id: string;
}>;

// Source: src/sanity/queries/index.ts
// Variable: REVIEW_QUERY
// Query: *[_type == 'review' && _id == $id]{    _id,    _createdAt,    body,    rating,    difficulty,    workload,    authorId,    course->{      name,      "slug": slug.current    },    semester->{      startDate,      term    },}[0]
export type REVIEW_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  body: string | null;
  rating: number | null;
  difficulty: number | null;
  workload: number | null;
  authorId: string | null;
  course: {
    name: string | null;
    slug: string | null;
  } | null;
  semester: {
    startDate: string | null;
    term: "fall" | "spring" | "summer" | null;
  } | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: COURSES_AND_RECENT_SEMESTERS_QUERY
// Query: {  "courses": *[_type == 'course'] {    "id": _id,    "slug": slug.current,    name  } | order(name),  "semesters" : *[_type == 'semester' && startDate <= now()] {    "id": _id,    startDate,    term  } | order(startDate desc)[0...$limit]}
export type COURSES_AND_RECENT_SEMESTERS_QUERY_RESULT = {
  courses: Array<{
    id: string;
    slug: string | null;
    name: string | null;
  }>;
  semesters: Array<{
    id: string;
    startDate: string | null;
    term: "fall" | "spring" | "summer" | null;
  }>;
};

// Source: src/sanity/queries/index.ts
// Variable: GET_COURSES_WITH_REVIEWS_STATS_QUERY
// Query: *[_type == 'course']{  ...,  "slug": slug.current,  "id": _id,  "reviews": *[_type == 'review' && references(^._id)]{    "id": _id,    "created": _createdAt,    ...,    "body": "",    "course": null,  }}
export type GET_COURSES_WITH_REVIEWS_STATS_QUERY_RESULT = Array<{
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  codes?: Array<string>;
  programs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "program";
  }>;
  description?: string;
  creditHours?: number;
  syllabus?: Syllabus;
  textbooks?: Array<
    {
      _key: string;
    } & Textbook
  >;
  officialURL?: string;
  notesURL?: string;
  tags?: Array<string>;
  isDeprecated?: boolean;
  isFoundational?: boolean;
  id: string;
  reviews: Array<{
    id: string;
    created: string;
    _id: string;
    _type: "review";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    course: null;
    semester?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "semester";
    };
    body: "";
    rating?: number;
    difficulty?: number;
    workload?: number;
    authorId?: string;
  }>;
}>;

declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == 'review']{\n  _id,\n  _createdAt,\n  body,\n  rating,\n  difficulty,\n  workload,\n  authorId,\n  semester->{\n    startDate,\n    term\n  },\n  course->{\n    name,\n    \"slug\": slug.current,\n  }\n} | order(_createdAt desc)[0...100]\n": RECENT_REVIEWS_QUERY_RESULT;
    "\n*[_type == 'course'] {\n  \"slug\": slug.current,\n}\n": COURSE_SLUGS_QUERY_RESULT;
    '\n*[_type == \'course\' && slug.current == $slug]{\n  ...,\n  "slug": slug.current,\n  "syllabusUrl": coalesce(syllabus.file.asset->url, syllabus.url),\n  programs[]->{acronym},\n  "reviews": *[_type == \'review\' && references(^._id)]{\n    _id,\n    _createdAt,\n    body,\n    rating,\n    difficulty,\n    workload,\n    authorId,\n    "course": null,\n    semester->{\n      startDate,\n      term\n    },\n  } | order(created desc)\n}[0]\n': COURSE_WITH_REVIEWS_QUERY_RESULT;
    "\n*[_type == 'course' && slug.current == $slug] {\n  name\n}[0]\n": COURSE_REVIEWS_PAGE_METADATA_QUERY_RESULT;
    "\n*[_type == 'review'] {\n  \"id\": _id\n}[0...$limit]\n": REVIEW_IDS_QUERY_RESULT;
    "\n*[_type == 'review' && _id == $id]{\n    _id,\n    _createdAt,\n    body,\n    rating,\n    difficulty,\n    workload,\n    authorId,\n    course->{\n      name,\n      \"slug\": slug.current\n    },\n    semester->{\n      startDate,\n      term\n    },\n}[0]\n": REVIEW_QUERY_RESULT;
    '\n{\n  "courses": *[_type == \'course\'] {\n    "id": _id,\n    "slug": slug.current,\n    name\n  } | order(name),\n  "semesters" : *[_type == \'semester\' && startDate <= now()] {\n    "id": _id,\n    startDate,\n    term\n  } | order(startDate desc)[0...$limit]\n}\n': COURSES_AND_RECENT_SEMESTERS_QUERY_RESULT;
    '\n*[_type == \'course\']{\n  ...,\n  "slug": slug.current,\n  "id": _id,\n  "reviews": *[_type == \'review\' && references(^._id)]{\n    "id": _id,\n    "created": _createdAt,\n    ...,\n    "body": "",\n    "course": null,\n  }\n}\n': GET_COURSES_WITH_REVIEWS_STATS_QUERY_RESULT;
  }
}
